version: "3.8"
services:
    mysql:
        image: mysql:8.0.20
        ports:
            - "3306:3306"
        volumes:
            - /c/docker-data/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: topSecret