version: '3'
services:
    mongoDB:
        image: mongo:3.6.18
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_db:/data/db
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:27017"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: topSecret
        command: mongod              

    mongoexpress:
        image: mongo-express:0.54
        links:
            - mongoDB:mongo
        ports:
            - "18081:8081"
        restart: always
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=topSecret
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=secret
        #command: sh -c 'sleep 10 && tini -- node app'

volumes:
    mongo_db:
        external: true