version: "3.2"
services:
 redis:
    image: "redis:6.0.3"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
     - "6379:6379"
    volumes:
     - //c/docker-data/redis:/data
     - ../config/redis/redis.conf:/usr/local/etc/redis/redis.conf  